name: test
on:
  push:
    branches:
    - 'main'
    - 'master'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # Test node 14/16/18/20/22 on ubuntu
      # Test node 20 on macos/windows
      # Enable annotations only for node 20 + ubuntu
      matrix:
        os: [ubuntu-latest]
        node: [16, 18, 20, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: npm ci
        run: npm ci

      - name: test
        run: npm run test
